-- Create base tables matching JPA entity names and backup structure

-- Ministerio table (singular, matches JPA entity)
CREATE TABLE ministerio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

-- Membro table (singular, matches JPA entity)
CREATE TABLE membro (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN,
    data_nascimento DATE,
    idade INTEGER,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(255)
);

-- Evento table (singular, matches JPA entity)
CREATE TABLE evento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) NOT NULL,
    contagem_homens INTEGER,
    contagem_mulheres INTEGER,
    contagem_total INTEGER,
    contagem_visitantes INTEGER,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    data DATE NOT NULL,
    observacao TEXT
);

-- Junction table for many-to-many relationship between membro and ministerio
CREATE TABLE membro_ministerio (
    membro_id INTEGER NOT NULL,
    ministerio_id INTEGER NOT NULL,
    PRIMARY KEY (membro_id, ministerio_id),
    CONSTRAINT fk_membro_ministerio_membro 
        FOREIGN KEY (membro_id) REFERENCES membro(id),
    CONSTRAINT fk_membro_ministerio_ministerio 
        FOREIGN KEY (ministerio_id) REFERENCES ministerio(id)
);

-- Junction table for many-to-many relationship between evento and ministerio
CREATE TABLE evento_ministerio (
    evento_id INTEGER NOT NULL,
    quantidade INTEGER,
    ministerio_id INTEGER NOT NULL,
    PRIMARY KEY (evento_id, ministerio_id),
    CONSTRAINT fk_evento_ministerio_evento 
        FOREIGN KEY (evento_id) REFERENCES evento(id),
    CONSTRAINT fk_evento_ministerio_ministerio 
        FOREIGN KEY (ministerio_id) REFERENCES ministerio(id)
);